### ISSUE TITLE
os.environb suppport?

### ISSUE THREAD

**Issue by abathur** [jmcs/ecological#15]
While trying to sort out storing/retrieving binary values in an env var on Heroku, I noticed that ecological only used `os.environ` and not also `os.environb`. 

I don't know if it's useful to add; just wanted to let you know in case you hadn't considered it. It didn't matter in our case; the Heroku CLI didn't support setting the binary value in the first place, so I fell back on using base64 which worked equivalently for both `environ` and `environb`.

**Comment by marcinzaremba** [comment]
For me it sounds like really easy change that can be implemented in a very generic, useful way.

First introduce a concept of `source` on `Variable` class and pass it as the constructor parameter; the protocol here would be `source` is a dictionary that `Variable` reads values from where `os.environ` stays the default one. Then utilizing `os.environb` would be trivial from user POV:
```
class Configuration(ecological.AutoConfig):
    my_var1: str = ecological.Variable("my_var1", source=os.environb)
```

**Comment by thilp** [comment]
Would there be a way to also specify `source` as "class argument", just like `prefix`? (I think you would have all your values coming from the same dict much more often than from different dicts.)

**Comment by marcinzaremba** [comment]
That's a great idea. We can support both actually. If `source` is provided on class then it overrides the settings on `Variable`. However in this case (when source would be `os.environb`) my thinking is it is undesirable to have it globally because it would be very painful for user to convert from `bytes` to `str` for example:
```
# Given that the transform func on Variable is the default cast
>>> from ecological import config
>>> config.cast(b'My value', str)
"b'My value'"
```
