### ISSUE TITLE
Failed if missing and/or Lazy Loading?

### ISSUE THREAD

**Issue by erewok** [jmcs/ecological#16]
Hello,

First I want to say thanks for building this library. I've built many versions of this idea for years and I think this is cleaner than any of my attempts.

I have two things I'd like to include, though, and I wonder if you'd be in interested in them as pull requests. Both are potentially opinionated, though, so feel free to tell me if they don't fit here.

For the first, I often have variables I'd like to exist in the environment and if they don't I want to fail immediately. I usually raise exceptions when parsing these environment variables if they're not present. Thus, I was thinking about a `required` argument to your variable class that raises when the variable is not present or false-y in the environment.

For the second, and this isn't a big deal, but I often like to have variables lazy-loading, so they only get parsed from the environment on first access, instead of as class attributes that get parsed and loaded as soon as the class is imported.

I would be happy to contribute one or both of these as pull requests for review if you think they may have a place in this project.

As it is, I think this is a cool library, so thanks for publishing it and putting it on PyPi.

**Comment by erewok** [comment]
You know, I must have misread this on first pass because it pretty much does what I was thinking of by having a `required` kwarg:

```python
        try:
            raw_value = os.environ[self.name]
        except KeyError:
            if self.default is _NO_DEFAULT:
                raise AttributeError(f"Configuration error: '{self.name}' is not set.")
            else:
               return self.default
```

I guess I still wonder if it would be worth it to make it *explicit* that a `Variable` without a default is *always* required. Sometimes it'll be okay if they're `None`? Hmm.

**Comment by marcinzaremba** [comment]
Hey @erewok. Thanks for reporting those. It's been a long time since this issue was opened so I will close it for now. Feel free to open anytime if have something new ;)
