### ISSUE TITLE
pypi / source distribution

### ISSUE THREAD

**Issue by abathur** [jmcs/ecological#19]
@jmcs I'm testing out a dependency-management tool for the nix language / package manager, and it failed when it couldn't find a source distribution for ecological on pypi.

Can you look into uploading one? :)

**Comment by jmcs** [comment]
[Done](https://files.pythonhosted.org/packages/55/be/b337f585b413ebd9c8ed4ae58854b036fed42ccc717cc776d663d13a50de/ecological-1.6.0.tar.gz)
